#!/bin/sh

BINARIES=(
# programs binaries
"$HOME/.deno/bin"
"$HOME/.cargo/bin"
"$HOME/.config/yarn/bin"
"$HOME/.pyenv/bin"
# personnal binaries
"$HOME/.local/bin"
"$HOME/.local/workbin"
)

for p in "${BINARIES[@]}"; do
	[ -d "$p" ] && export PATH="$p:$PATH"
done

[ $(command -v "ssg-agent") ] && eval "$(ssh-agent -s)"
[ $(command -v "ssg-add") ] && [ -d "$HOME/.ssh/id_rsa.pub" ] && ssh-add "$HOME/.ssh/id_rsa.pub"

export LESSHISTFILE="-"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export ZDOTDIR="$HOME/.config/zsh"
export INPUTRC="$HOME/.config/inputrc"
export WGETRC="$HOME/.config/wget/wgetrc"
export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
export MANPAGER="nvim -c 'set ft=man' -"
# default programs
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

# if [ $(tty | grep "tty") ] && [ ! $(pgrep Xorg) ]; then
#     killall -9 i3 &>/dev/null
#     exec startx &>/dev/null
# fi

# wayland
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland-egl
export GDK_BACKEND=wayland
export CLUTTER_BACKEND=wayland
export XDG_CURRENT_DESKTOP=Unity

if [ "$(tty)" = "/dev/tty1" ]; then
    exec sway &>/dev/null
fi
