#!/bin/sh

xmodmap "$HOME/.Xmodmap"
xrdb -merge "$HOME/.Xresources"

xset r rate 300 40 &   # Set writing rate
nm-applet &            # Wifi tray
sxhkd &                # Launch key bindings
mpd &                  # Music daemon
setbg &                # Sets the background
unclutter &            # Hides the cursor
picom -b &             # Compositor

exec i3
