" My   "
" Vim  "
" Rc   "
" File "

let mapleader =" "

call plug#begin('~/.vim/plugged')
	Plug 'junegunn/goyo.vim'
	Plug 'PotatoesMaster/i3-vim-syntax'
	Plug 'scrooloose/nerdtree'
	Plug 'drewtempelmeyer/palenight.vim'
	Plug 'itchyny/lightline.vim'
call plug#end()

set background=dark
colorscheme palenight

let g:lightline = {
	\'colorscheme': 'palenight',
	\}

if (has("nvim"))
	let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

if (has("termguicolors"))
	set termguicolors
endif

" bg transparent
"hi Normal ctermbg=none guibg=NONE

syntax on
set number relativenumber
set ruler
set cursorline

"Activate indentation
filetype off
"Disable vi-compatibility
set nocompatible
set encoding=utf-8
set wildmode=longest,list,full
filetype plugin indent on
set smartindent
"Non-expanded, 4-wide tabulations
set tabstop=4
set shiftwidth=4
set noexpandtab
"Don't bother throttling tty
set ttyfast
"More useful backspace behavior
set backspace=indent,eol,start
"Use statusbar on all windows
set laststatus=2
"Better search
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
"
" Automatically deletes all trailing whitespace on save.
autocmd BufWritePre * %s/\s\+$//e
" Run xrdb whenever Xdefaults or Xresources are updated.
autocmd BufWritePost ~/.Xresources,~/.Xdefaults !xrdb %

" disable autocommenting on newline
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" goyo plugin to read text better
map <leader>f :Goyo \| set linebreak<CR>
"nerd tree
map <C-n> :NERDTreeToggle<CR>

" Splits open at the bottom and right, which is non-retarded, unlike vim defaults.
set splitbelow splitright

"disable arrow keys
noremap <Left> <Nop>
noremap <Right> <Nop>
noremap <Up> <Nop>
noremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>

"map control hjkl to move between windows (no need for w)
noremap <C-h> <C-W>h
noremap <C-j> <C-W>j
noremap <C-k> <C-W>k
noremap <C-l> <C-W>l


