# see /usr/share/doc/alacritty/example/alacritty.yml
env:
    TERM: xterm-256color

window:
  dimensions:
    columns: 0
    lines: 0

  dynamic_title: true
  padding:
    x: 4
    y: 0

  dynamic_padding: false
  decorations: none
  startup_mode: Maximized

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: "monospace"
    style: Regular

  bold:
    family: "monospace"
    style: Bold

  italic:
    family: "IBM Plex Mono Medium"
    style: Italic

  size: 14

  offset:
    x: 0
    y: -2

  glyph_offset:
    x: 0
    y: 0

use_thin_strokes: true
draw_bold_text_with_bright_colors: true

colors:
  vi_mode_cursor:
   text: '#1b1e2b'
   cursor: '#89ddff'

  selection:
   text: '#a6accd'
   background: '#32374d'

  cursor:
    text:   '#1b1e2b'
    cursor: '#a6accd'

  # Default colors
  primary:
    background: '#1b1e2b'
    foreground: '#ffffff'

  # Normal colors
  normal:
    black:   '#1b1e2b'
    red:     '#d06178'
    green:   '#b4c4b4'
    yellow:  '#b4b4b4'
    blue:    '#959dcb'
    magenta: '#a9a3db'
    cyan:    '#89bbdd'
    white:   '#a6accd'

  # Bright colors
  bright:
    black:   '#292d3e'
    red:     '#e61f44'
    green:   '#d0e7d0'
    yellow:  '#cfcfbf'
    blue:    '#b8bcf3'
    magenta: '#b9a3eb'
    cyan:    '#89ddff'
    white:   '#ffffff'

bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'

background_opacity: 1

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false

  url:
    launcher: xdg-open
    modifiers: Control

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
alt_send_esc: false

debug:
    render_time: false
    persistent_logging: false
    log_level: Warn
    print_events: false
    ref_test: false

key_bindings:
  - { key: Paste,                   action: Paste                        }
  - { key: Copy,                    action: Copy                         }
  - { key: A,        mods: Control, action: ToggleViMode                 }
  - { key: J,        mods: Control, mode: Vi, action: ToggleViMode       }
  - { key: Slash,    mods: Control, chars: "++"                          } # allow control slash to send ++ so i can bind control / to comment in vim
  - { key: Backslash,mods: Control, chars: "\x1b[C"                      } # allow control backslash to send right so i can complete zsh autocompletion easily

