syntax on
set nu
set ruler
set cursorline

"|gruvbox|hybrid_reverse|jellybeans|snazzy|tender
colorscheme snazzy
"nerd tree
map <C-n> :NERDTreeToggle<CR>

"black zone after 80
set colorcolumn=80
let &colorcolumn=join(range(81,999),",")

"disable arrow keys
noremap <Left> <Nop>
noremap <Right> <Nop>
noremap <Up> <Nop>
noremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>

"map control hjkl to move between windows (no need for w)
noremap <C-h> <C-W>h
noremap <C-j> <C-W>j
noremap <C-k> <C-W>k
noremap <C-l> <C-W>l
	
"Activate indentation
filetype off
filetype plugin indent on
set smartindent

"Non-expanded, 4-wide tabulations
set tabstop=4
set shiftwidth=4
set noexpandtab

"Disable vi-compatibility
set nocompatible

"Real-world encoding
set encoding=utf-8

"Interpret modelines in files
set modelines=1

"Do not abandon buffers
set hidden

"Don't bother throttling tty
set ttyfast

"More useful backspace behavior
set backspace=indent,eol,start

"Use statusbar on all windows
set laststatus=2

"Better search
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch

"enable pathogen or runtimepath for plugin loading
execute pathogen#infect()
"set runtimepath^=~/.vim/bundle/*

