#!/bin/bash

battery=$(acpi | awk '{print $4}')
temp=$(acpi -t | awk '{print $4" °C"}')
echo -e "<span color='yellow'>battery ${battery}</span><span> | </span><span color='orange'>temp ${temp}</span>"

