export ZSH="/home/kiyan/.oh-my-zsh"

ZSH_THEME=""

fpath+=('/home/kiyan/.zsh_functions')

plugins=(git zsh-autosuggestions docker colored-man-pages)

if [[ $PLUG_PY == 1 ]]; then
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
	plugins+=(pyenv)
fi

source $ZSH/oh-my-zsh.sh

[ -f '/home/kiyan/.gcloud/path.zsh.inc' ] && . '/home/kiyan/.gcloud/path.zsh.inc'
[ -f '/home/kiyan/.gcloud/completion.zsh.inc' ] && . '/home/kiyan/.gcloud/completion.zsh.inc'

# my config
alias pacman="sudo pacman"
alias cht="curl cheat.sh/"
alias gitbeauty="git log --all --graph --oneline"
alias ls="exa"
alias la="ls -la --git"
alias vim="nvim"
alias open="xdg-open"
alias find="fd"
alias cdd="cd $HOME/Document/workspaces"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="rg --hidden -l "" -g '!.git' ."

autoload -U promptinit; promptinit
prompt pure

source /home/kiyan/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
