# start oh my zsh
export ZSH="/home/kiyan/.oh-my-zsh"

ZSH_THEME=""

fpath+=('/home/kiyan/.zsh_functions')

if [[ $PLUG_PY == 1 ]]; then
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
	plugins=(git zsh-autosuggestions docker colored-man-pages ripgrep pyenv)
else
	plugins=(git zsh-autosuggestions docker colored-man-pages ripgrep yarn)
fi

[ -f '/home/kiyan/.gcloud/path.zsh.inc' ] && . '/home/kiyan/.gcloud/path.zsh.inc'
[ -f '/home/kiyan/.gcloud/completion.zsh.inc' ] && . '/home/kiyan/.gcloud/completion.zsh.inc'
[ -d '/home/kiyan/.yarn/bin' ] && export PATH="$HOME/.yarn/bin":$PATH

source $ZSH/oh-my-zsh.sh

# add cargo
[ -f '$HOME/.cargo/bin' ] && export PATH=$HOME/cargo.bin:$PATH

# my config
alias pacman="sudo pacman"
alias gitbeauty="git log --all --graph --oneline"
alias ls="exa"
alias la="ls -la --git"
alias vim="nvim"
alias open="xdg-open"
alias find="fd"
alias cdd="cd $HOME/Document/workspaces"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="rg --hidden -l "" -g '!.git' ."

autoload -U promptinit; promptinit
prompt pure

source /home/kiyan/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
