# configure oh my zsh
ZSH_THEME=""
export ZSH="$HOME/.oh-my-zsh"
plugins=(git zsh-autosuggestions docker colored-man-pages vi-mode)

# launch oh my zsh
source $ZSH/oh-my-zsh.sh

# open stuff mac style
function open() {
	&>/dev/null xdg-open $1 &
	disown
}

# aliases
alias pacman="sudo pacman"
alias cht="curl cheat.sh/"
alias gitbeauty="git log --all --graph --oneline"
alias ls="exa"
alias la="exa -la --git"
alias lt="exa -Tla --git"
alias vim="nvim"
alias find="fd"
alias grep="rg"
alias less="bat"

# fzf plugin for fast search
# `bindkey | grep fzf` for the key bindings
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
[ $(command -v fzf) ] && export FZF_DEFAULT_COMMAND="rg --hidden -l "" -g '!.git' ."

# the prompt
[ $(command -v starship) ] && eval "$(starship init zsh)"

# must be sourced after starship
source $HOME/.zsh_vi_mode

# add syntax highlighting to zsh
[ -d $HOME/.zsh-syntax-highlighting ] && source $HOME/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
