#!/bin/bash

GR='\033[0;32m'
BL='\033[0;34m'
RS='\033[0m'

ip=$(hostname --ip-addresses | awk '{ print $1 }')
wip=$(curl -s https://ipinfo.io/ip)
echo -e "<span color='lightgreen'>${ip}</span><span> | </span><span color='lightblue'>${wip}</span>\n"

